### ISSUE TITLE
[Feature Request] Record TV (DVR feature) save video stream to local disk

### ISSUE THREAD

**Issue by Hedda** [djp952/pvr.hdhomerundvr#10]
@djp952 I like to make a feature suggestion, that is to add local recording functionality into this PVR client addon.

In summery; I would like to request the ability for this PVR client addons to perform local video recording / stream saving to files on the local file-system. That is, so enable local recording without an active HDHomeRun RECORD storage device on the local network or a subscription to the SiliconDust HDHomeRun DVR Service. Totally stand-alone local recordings done by the PVR client itself without any external PVR backend or DVR service what so ever.

From a user-experince point of view it would be great for an option have the ability to "record to local disk" inside this native HDHomeRun PVR client addon. In function for this, the PVR client addon would be able act a completly stand-alone DVR (Digital Video Recorder) on its own when used in Kodi (which I beleiev would be especially of interest to Kodi users running Android without having any NAS or PC to run a backend on). That is, for the PVR client addon itself to save individual video streams locally to a disk directory/folder on the local file-system. Preferably for the PVR client addon to even save as video files in MPEG-TS (.TS) format just like real stand-alone DVR devices.

This ability to do stand-alone recordings could also lead more DVRs stand-alone features which have dependency on recording, like the ability to "Pause" and "Rewind" Live TV for timeshifting if could add the possibility to continuously record a video streaming from a networked-attached HDHomeRun tuner to a series of temporary files in a look, again acting just like a read stand-alone DVRs (DVR boxes).

As you know, compaing to other PVR client addons for Kodi, all such recording functionality is normally located and dependent in an external PVR/DVR backend instead of the PVR client addon itself, (just as your PVR client addon is currently dependent on SiliconDuct's HDHomeRun DVR service as a PVR backend) but this addon is kind-of special and somewhat unique in that it connects to the (network-attached) TV-tuner directly, streaming directly from, so technically it could be changed so it would not actually have to go through a  PVR backend at all which can bring such local recording functionality. And in addition it would be very nice to have the ability for the video files to be saved locally directly on an Android device (or more specicially local direct attached USB storage) instead of on the PVR/DVR backend or NAS.

PS: FYI; I have previously already made this request to your competing PVR client addon author @zcsizmadia here: https://github.com/kodi-pvr/pvr.hdhomerun/issues/7 who initially said that he definitely planed to add this feature but later just closed the request without comment.

**Comment by Hedda** [comment]
Here are a couple of links to forks of the Simple IPTV PVR client with added code (by rkubera, with updates by simphax) which features a simple recording feature which adds timeshifting functionality, perhaps you could have a look at this code for possible integration into this native HDHomeRun PVR client addon?

https://github.com/rkubera/pvr.iptvsimple/

https://github.com/simphax/pvr.iptvsimple

This request have also been mentioned in the forum thread with the comment "Just imagine all Android boxes that will then be able to act as a full featured DVR with Kodi and HDHomeRun without a external backend." And please note that Nate from the Kodi team and president of the XBMC Foundation posted in the native HDHomeRun PVR client addon forum thread not long ago and requested this feature himself:

http://forum.kodi.tv/showthread.php?tid=246658

Point is for this addons to have this capability nativly is just these few unique stand-alone client addons without the need to use a standa-alone PVR backend software application.

Would it be maybe interested in copying and implementing rkubera's native code for recording into your stand-alone HDHomeRun PVR client addon as a proof-of-concept? See rkubera commits here:

https://github.com/rkubera/pvr.iptvsimple/

Maybe look at the code by rkubera for recording to a PVR client addon?

https://github.com/simphax/pvr.iptvsimple/tree/master/src

@rkubera added stream recording code to Simple IPTV PVR client addon, including multi-recording with ffmpeg binary integration. And @simphax is kept an update dfork of of his recording branch:

https://github.com/simphax/pvr.iptvsimple/commits/recording

**Comment by djp952** [comment]
Hi Hedda! I get where you're coming from on this.  I fear the complexity involved goes well beyond the scope of what I'm trying to do with this particular project, but I am always open to suggestions and I'm not always right in how I initially consider them, so please feel free to try and convince! I won't close your issue without a comment - promise.

It isn't very hard at all to take what the tuner(s) are sending and save it off as a recorded TV file, and we can even get the metadata for naming and whatnot from the free 4-hour guide data provided by SiliconDust.  It's when you start getting into the details that things start to spiral out of control :)

First off we have scheduling.  We would need a service/daemon of some kind to handle this, otherwise you end up limited to just selecting what's currently on a channel and recording that.  While such a thing could exist inside Kodi, that makes it totally dependent upon Kodi running, if you exit Kodi everything would completely cease.

Then we have the buffering/timeshifting concern -- as you've researched it takes a lot to get this right, the most elegant solution being to always write to disk and play back live TV from there.  This is how Microsoft Media Center works, too.  If you stop playback and never opted to record, you just delete the temporary file.  While elegant, this unfortunately is way different than what I'm doing today, I'm relying upon the HTTP streams provided by the HDHomeRun RECORD engine.  Not saying it's not possible, it clearly IS possible, but we're already going down the path that leads to a separate project.  The way this client is designed it would be a little crazy to try and work such a fundamental difference alongside the existing functionality.

There are some other little nits that pop-up like how Kodi behaves when you press the Record button in the player (it adds a timer), but those types of things can be worked around pretty easily.  They get a little complicated if you don't have a disk buffer already and then expect to be able to timeshift, but again these are just details :)

To really flesh this out to be workable for most people the end result would take a long time and ultimately be very similar to what SiliconDust already provides with their DVR service.  Granted, their UI isn't everyone's cup of tea and they have some unique methods for how DVR scheduling should work, but they've done the work and provide a rather complete solution.  It's not free, of course, and I understand that is a factor for many people.

Marrying the existing functionality of this client with an in-built DVR solution just feels too prohibitive.  I actually think the official Kodi addon is a better choice since it doesn't currently leverage the HDHomeRun DVR system, and I think it's a shame the idea was closed out without more consideration.  One thought I've had as well is that there is no reason (other than time and interest) Kodi itself couldn't provide this functionality, it has access to all the tuners and the EPG and everything for all supported systems, it shouldn't be too much of a stretch to add the necessary scheduling and recording management right into the application itself, then everyone could use it!

Have you considered going down the path of perhaps using this and the official HDHomeRun PVR client code as a base and maybe starting your own project?  I really think adding DVR functions is best served as a separate thing if the official one will never support it.  I'd be happy to help if I can, and I'd be flattered if this project could serve as the basis for another with different cool features!

**Comment by djp952** [comment]
I'm also going to try and get you in touch with at least one person that recently had ambition to take the available HDHomeRun client(s) for Kodi in a new direction.  Let me touch base with him and see if he's still interested in his project, if he is I'd expect local recording is at or near the top of his list.  You can also check the SiliconDust forum, there is a user named RockerC that is looking for this functionality as well.  If you all got together I'd bet the end result could be pretty amazing.

**Comment by Hedda** [comment]
Thanks for the reply! I would be cool with it being totally dependent on having Kodi up-and-running, and it not being an external recording service separate from Kodi. For such a simple recording function without an external scheduling service, a shutdown Kodi or Kodi crash and any active recording stopping or being corrupt/deleted is absolutly OK and fully acceptable IMHO for this type of solution. The core point of this would to have only "Kodi" installed on an Android TV box and an HDHomeRun tuner with no other devices or external services running on other third-party devices like a NAS. Less hardware requirements and a much simpler setup, but then also a heavily compromise on the available features.

As RockerC wrote in SiliconDust forum https://forum.silicondust.com/forum/viewtopic.php?f=88&p=299965#p299965

Maybe have a user configuration for maximum time/size for each recoding, with a estimated default setting set. Say example defaults of 4-hours for standard manually started recordings becore the software to automatically stop recording if the user does not manually stop the active recording. If done via the EPG then gets a little more advanced as you would have to calculate the how long to leave recording on based on EPG info.

Regardsless, first I would suggest that the user would get to set a recording directory (if not system default) as well as a user allocated total limit of how many hours (based on standard bitrate) and/or maximum file-size can be used for all recordings on the system. 

Similar to popular DVR boxes such TiVo where many DVR box specifications only lists how many hours the box is capable of recoding in HD and SD resolutions, and not actually how large the harddrive is or how many GigaByte of usage space is available for recording. 

Standard Deffinition (480p) 1080p recordings typically consume around 1GB per hour if saving a H.264 stream. High Deffinition (1080p) recordings typically consume around 5GB per hour if saving a H.264 encoded stream. However if you are saving a MPEG-2 encoded stream then you need to double those estimates. 

So if you would allow the user to just configuration recording directory and how many hours of SD or HD quality video they want to record then the software could automatically calculate and estimate how much disk-space that so and so many hours of SD and HD quality video that person could record on his choosen storage.

For timeshifting (pause Live TV) it gets a little more complicated as you then would probably want have the user allocate the number of hours he/she can timeshift to again determen estimated disk-space allocation, and then on the technical-side you would not want do the timeshifting recoding to one large file, but instead do the timeshifting recording in chunks to many smaller files (maybe only 100MB per file), as that way you can delete the older files one-by-one in order to make room for new files before you reach the allocated disk-space for timeshifting set by the users by how many hours they allow for timeshifting. (Kind of like using log-rotation methods https://en.wikipedia.org/wiki/Log_rotation ).

**Comment by djp952** [comment]
FYI: I've asked the folks at the SiliconDust forums that also would like and have input for local recording to come here and use this Issue as a sounding board for now as well.  I think if we pursue this it will ultimately be a separate project that doesn't overlap with the SiliconDust services :)

**Comment by djp952** [comment]
I'm going to close this one out as "won't implement", it's been about a month with no new feedback.  I haven't changed my mind on whether to include this in the current PVR client, but my offer is still good to help out with or contribute to a fork that does include that feature.  Sorry to disappoint!!

Besides, there are still more than enough little problems to solve with the features it already has! LOL.

I wish you all the best with getting this feature somehow/somewhere!! :)

**Comment by Hedda** [comment]
@djp952 FYI @fuzzard have submitted a PR upstream for the HDHomeRun PVR addon that implements this "in a rough fashion", however unfortunatly he have not continued to develop it, but at least it is a base to build on if someone wanted to. See => https://github.com/kodi-pvr/pvr.hdhomerun/issues/7
