### ISSUE TITLE
Channel Guide Missing on Fire TV Cube

### ISSUE THREAD

**Issue by abrombo** [djp952/pvr.hdhomerundvr#117]
I have loaded kodi and your hdhomerun add on to my Fire TV Cube.  Everything works except the channel guide for the hdhomerun.  It is empty.  Note that the channel guide works on all my Ubuntu 20.04 linux computers.

**Comment by djp952** [comment]
Hi!  Sorry for the 14-hour delay here in responding.

The "best" way to start figuring this out would be to get a copy of a Kodi log from the Fire TV Cube. It's very likely that some type of error is occurring that is preventing this from working that would have been logged, but I freely admit that over the years some really weird things have happened here and it might take more work.

Using the guide here as the location (for Android): https://kodi.wiki/view/Log_file, do you think there is a way you can get me a copy of the Fire TV Cube's kodi.log and kodi.old.log files? It's cool if that's not possible, we can work this another way if we need to.  If you able to grab these files, you can use https://paste.kodi.tv to paste their contents legitimately since it's Kodi, and just provide the link(s), or I can give you an e-mail address to send them to me.

Over the years, unfortunately, there have been a lot of really weird things that can cause the EPG to fail. As far as I know all of it has been fixed and it's most likely a failure to get the data from a network-level reason, but I don't want to provide any seemingly flippant/dismissive responses here. It's legit just as likely that you have encountered a new defect/bug as it is your device has encountered a new HDHomeRun ecosystem concern that I have not corrected for.

I do apologize you are having problems, the current version of the addon has been extremely stable to my knowledge. Rest assured that I will help figure this out?

**Comment by djp952** [comment]
Did you ever find a solution to this? I apologize for doing this, but I've moved this project into "maintenance mode" (nothing new, just required fixes) and it's been a long time so I'm going to flag this one as closed? I'm not dead, if you are still having problems please let me know, OK?
