### ISSUE TITLE
Upgrade to LibreELEC RPI 11.0 7-23 Nightly causes boot loop with pvr.hdhomerundvr enabled

### ISSUE THREAD

**Issue by ubernewy** [djp952/pvr.hdhomerundvr#120]
Upgrading to LibreELEC RPI 11.0 7-23 Nightly caused a boot loop that required the removal of the pvr.hdhomerundvr addon in safe mode. Reinstalling the latest Nexus version nexus-v20.8.1.8078 causes the same issue. There seemed to be an update that was done in LibreELEC that caused an issue with many binary addons. Cleaning and reinstalling the Kodi/LibreELEC repository addon pvr.hdhomerun does work. More information on the issue is discussed in the below thread. Attempting to install nexus-v20.8.1.8078 on the latest 10-03 nightly causes a dependency error on kodi.binary.global.main version 1.3.0.

[https://forum.libreelec.tv/thread/25886-libreelec-rpi2-arm-11-0-nightly-20220723-boot-loop-after-kodi-image/](url)

**Comment by djp952** [comment]
I apologize for such a long delay in response, that's uncool. Are you still having problems with this?

**Comment by ubernewy** [comment]
No way man . Totally no worries. We appreciate you and all the time you dedicate to help us in the community. I just loaded up the LibreELEC RPI 11.0 2023-01-09 Nightly along with your latest nexus-v20.9.0.8408 release. It is working great with Live TV and DVR. The new release is also working great for me on Android/Fire TV as well on the latest Nexus nightly.  Thanks again for all your hard work and effort. You are very much appreciated.

**Comment by djp952** [comment]
Glad to hear it, especially since (kind of / mostly) ignoring this project for nearly a year now :) Releases will be far less frequent moving forward (unless something truly bad happens, I'll be on that for you guys), but I'm extremely happy to hear the Android Nexus build is OK, I wasn't able to test that platform this time around and was very worried about it based on the scope of the SSL/TLS changes and so much time away.

This project isn't dead, I mean I still need to use it for all my TV viewing too :) It's maybe "walking dead"? LOL. I'm sure I'll have at least one or two new things once Nexus goes live and I install it and become disappointed with myself for missing out on some cool new thing I want :)

But hey, thanks for your patience, and I do sincerely apologize for spending the bulk of late 2022 totally checked out on you. I feel really bad about not seeing/responding to your inquiry for over 3 months.
