### ISSUE TITLE
Kodi Nexus 9-17 Nightly upgrade causes a compatibility issue with pvr.hdhomerundvr 

### ISSUE THREAD

**Issue by ubernewy** [djp952/pvr.hdhomerundvr#121]
Using the latest release nexus-v20.8.1.8078 the Kodi Nexus 9-17 Nightly upgrade (and subsequent releases) causes the addon to be incompatible. The API may have recently been bumped with the addition of the feature to use multiple instances of the same binary addon?

When enabling after Kodi has disabled the addon the log shows The Add-on is not compatible with this version of Kodi.
When trying to reinstall the log shows The dependency on kodi.binary,instance.pvr version 8.0.1 could not be satisfied.
When trying to install after modifying the addon.xml to import version 8.2.0 The log shows HDHomeRun DVR PVR Client is using an incompatible API version for type PVR. Kodi API min version - 8.2.0/8.2.0, add-on API version 8.0.0/8.0.2

This has been tested on Android and Fire TV devices.

**Comment by djp952** [comment]
I'll try to get to this as soon as this coming weekend and fix you up but am unable to match Kodi's "Nexus" release cadence right now, even though I happened to have been a contributing factor to this particular Nexus API change.

Hang tight if possible!

**Comment by ubernewy** [comment]
Is there a 20.9.0 Android arm release or .zip posted anywhere? I would definitely be on board to test it.

**Comment by djp952** [comment]
I've generally (and kind of suddenly?) "abandoned" this project at this point since Team Kodi feels that they do it better than I can. There are a lot of pending changes that I never committed or truly tested -- at this point in time I am only willing to "maintain this" for me but will still publish my changes due to new Kodi requirement that I have a need to adhere to.

As of this moment in time, I have zero intention to waste any more of my time supporting any "in-progress" Kodi releases anymore. When that release eventually goes live, I will need to adapt to it and will publish those changes for my own benefit, but while it was a good run, I am simply done with trying to be part of and/or being an influencer for "Team Kodi".

I do not mean or intend any offense here, but I've "walked away" from this project. I still need it until can also "walk away" from Kodi on my own terms, and anything I happen to need to change as Kodi evolves, I do intend to share.

I sincerely hope that Team Kodi picks up on my past work and makes it better and available for everyone, but I'm legit "out". I wouldn't' expect any more updates to this project unless those updates impede my particular TV viewing in some way?

I have much better things to do with my particular "time left", I'll be 50 next Monday, than waste it on this project anymore. If I need it to "work", and that serves my interests; I will publish it.

I'm honestly not in a position to answer this question? The "zuki" codebase is dead and I am not going to ressurect it.

**Comment by obliojoe** [comment]
I don't know where else to post this so I just want to say thanks so much for all of your work on this. We have used it in my home for years, instants on multiple TVs and it has worked beautifully for my family. I appreciate you. Happy birthday and good luck with future endeavors!

**Comment by djp952** [comment]
I did finally get around to a new Nexus build! I've only been able to test it on Windows so far, and there was a fairly major change in how SSL connections are treated, but I think that will be OK.  It requires Nexus RC1/RC2 or better.  I want to put out a beta for people to try, are you interested? It would be a link to a folder on OneDrive as opposed to here and a manual install from the .zip file.

Let me know what you think; if I can find the time to exercise it on Linux and Android and nobody finds any major flaws it might be official this coming weekend.

(There was a big problem with updating one of the dependencies based on how I support older Linux systems that I was finally able to get around)

**Comment by ubernewy** [comment]
Yes for sure. I would definitely be interested. I can easily test Windows, Raspbian armhf and Android ARM. Your addon is my main go to for live TV cable viewing. I also use the DVR as well. I really appreciate your time and effort.

**Comment by djp952** [comment]
I'm actually publishing it "for reals" as I write this, no need to use a Beta. It will take an hour or two, but if you check back in the morning (I'm in U.S. Eastern Time), there should be a shiny new version for Nexus available formally.  Again, apologies for this long delay.
