### ISSUE TITLE
scrolling fwd/back on live tv hangs

### ISSUE THREAD

**Issue by airdrummer** [djp952/pvr.hdhomerundvr#28]
while watching livetv, scrolling fwd/back eventually hangs kodi; i have to kill kodi from ssh/cli

**Comment by djp952** [comment]
Wow, you are having just an awful time airdrummer!  To be honest, I see this from time to time myself on Windows (Krypton) with Recorded TV.  I've not been able to pin it down to being a PVR issue or a Kodi/ffmpeg issue, since Kodi locks up on us the log isn't completed.  It would be better if it crashed, honestly :(

I got nothin' for you on this right now, but it does bug me too.  I would definitely like to find and correct the defect, if there is any discernable pattern to the behavior you see that would help a lot!  Any specific channels you see it on, are you scrolling back beyond the start or beyond the end (shifting back to Live)?

**Comment by airdrummer** [comment]
i'll give it a try, thanx

**Comment by djp952** [comment]
Marking this one as closed to clean out the issue log.  Please do not hesitate to reopen this or open a new issue if you continue to have problems, ok?
