### ISSUE TITLE
crash on record from guide

### ISSUE THREAD

**Issue by airdrummer** [djp952/pvr.hdhomerundvr#30]
everytime i try to select a program to record from the guide, kodi crashes.
i’m using zuki.pvr.hdhomerunpvr v1.2.8

logs at paste.osmc.tv/lefobefiha

**Comment by djp952** [comment]
I'm seeing a lot of timeout errors trying to get to the HDHomeRun guide data in this log.  For example:

ERROR: GetEPGForChannel failed due to an unhandled exception: SQL logic error (1): http request on [http://api.hdhomerun.com/api/guide?DeviceAuth={redacted}Channel=481&Start=1526965200] failed: Timeout was reached

I don't set the cURL timeouts over the defaults, which appear to be 300 seconds to connect to the server, and then 'never' for the actual web request.  Are you able to do a ping test from your system to "api.hdhomerun.com"?  This kinda feels like a DNS lookup issue, like your system is having trouble resolving the host name.   If you can't ping api.hdhomerun.com, or it takes a long time to come back the first time we may be on the right track

**Comment by djp952** [comment]
Marking this one as closed to clean out the issue log.  Please do not hesitate to reopen this or open a new issue if you continue to have problems, ok?
