### ISSUE TITLE
guide doesn't automatically update

### ISSUE THREAD

**Issue by airdrummer** [djp952/pvr.hdhomerundvr#31]
i have to manually bounce kodi, then i’m good until the guide empties…

**Comment by djp952** [comment]
Hard to know exactly what would cause this without logs, but based on your previous issue I think there is something going awry with your network connection or DNS lookups to api.hdhomerun.com.  Not sure why it would load up the first time and then be unable to, BUT: SiliconDust has seen clients banging against their backend with bad DeviceAuth codes, it's possible it was from this PVR client.  In version 1.2.9 (released a couple days ago) I made some changes so that if the backend query fails, the first thing I do is refresh the device list in case the codes are stale.  I also fixed a bug that was preventing the proper HTTP result code from being put into the Kodi logs, for example there was no way to know if the backend was returning an HTTP 401 or a 403 or whatever.

If you're game, can you update to version 1.2.9 and see if A) there is any difference and B) can you grab the Kodi log to look at?

Thanks!

**Comment by djp952** [comment]
Marking this one as closed to clean out the issue log.  Please do not hesitate to reopen this or open a new issue if you continue to have problems, ok?
