### ISSUE TITLE
Failing to load stream for HDHomerun premium channels

### ISSUE THREAD

**Issue by Gilbo125** [djp952/pvr.hdhomerundvr#35]
Running LibreElec 8.2.5 on a Raspberry Pi 3 with zuki.pvr.hdhomerundvr-linux-armhf-krypton-1.3.2.6799.  The addon worked fine while the new HDHomerun premium channels were in demo mode, however, after paying for the subscription the premium channels fail to load in Kodi.  

Also running hdhomerun_record_linux_20180817 on a server where recording is done.

**Comment by Gilbo125** [comment]
NEvermind, got it working...

**Comment by djp952** [comment]
OK cool!  Please don't hesitate to open any additional issues or ping me if you run into any problems with the new channels.  I only have the demo ones myself (already have CableCard) so I am somewhat in the dark on how well the real ones will behave.  They use a different encoding than regular OTA/Cable channels.

Good luck my friend, and thanks for letting me know (especially since I didn't have to do anything! LOL)

**Comment by Gilbo125** [comment]
Will do.  For reference, I had to disable the addon, stop the recording engine, power cycle the HDHomerun, restart the recording engine, and enable the addon.  Then it worked fine.  I think the engine was confused between the demo streams and actual streams after i purchased the subscription.  Working well so far.  Thanks.  

PS - the addon is awesome, thanks for all you do!
