### ISSUE TITLE
Rewind / FF Live TV not working

### ISSUE THREAD

**Issue by jlippold** [djp952/pvr.hdhomerundvr#41]
If this is the wrong place to ask these questions, please point me to the appropriate location. As I suspect this is a configuration issue, not a bug.

I successfully installed the addon, and I was able to add a recording via the Kodi UI on my OSMC RPI3. I notice that in the addon feature summary, it says that I can rewind and fast-forward live tv, but I'm having a hard time getting that feature to work. Is there something special that needs to be done to enable this feature, or is it a hardware limitation? Pause works fine.

Thanks again.

**Comment by jlippold** [comment]
Found this answer here that worked: https://forum.silicondust.com/forum/viewtopic.php?f=88&t=65776&p=309664&hilit=rewind+live#p309664

```
Hi clegg78! Based on the description, it *sounds* like the client is having trouble finding your HDHomeRun RECORD engine. This isn't entirely uncommon, and there is a setting that might help. First let's see if it found the RECORD engine. I'm assuming you're running Kodi 17.6 Krypton?

> In Kodi, go to Settings / PVR & Live TV settings
> At the bottom of the menu on the left-hand side, make sure the little gear icon says "Advanced" or "Expert" (click on it to change)
> If you highlight "Client Specific" on that left-hand menu, you will get a "Client specific settings" option in the main view. Click on that
> Click on "List discovered devices" from that list
> Do you see an entry that say "HDHomeRun RECORD" in the list?

If you don't see "HDHomeRun RECORD", that would pretty much explain all of the problems. You can try changing how the client finds the devices ...

> From the Kodi Addon Browser, go into "My add-ons" / "PVR Clients" / "HDHomeRun DVR PVR Client"
> Click on "Configure"
> In the "General" section there is an option called "Use network broadcast for device discovery". Turn that on.
> Restart Kodi, and see what happens

If you still don't see any recordings or an "HDHomeRun RECORD" device in that list, let us know. We can go from there
```

Thanks anyway, awesome addon btw

**Comment by djp952** [comment]
Glad you got it worked out!  I still have no idea why HTTP discovery doesn't work for everyone, but you found the exact thing I was going to say to try regardless.

I know the issue is closed, but since the PVR is in a state of lull right now I think I'll add an enhancement item to fall back to broadcast discovery if no RECORD engine is found via HTTP.  Something like if no RECORD engine is found, try again via broadcast.  If that finds it, automatically change the setting and pop up a message that it was changed.  I think that would be non-intrusive for the folks that use this PVR without a RECORD engine running yet save the TON of people that have this problem the aggravation involved of figuring out why it didn't work.

**Comment by jlippold** [comment]
That would be awesome. TBH, that was my only pain point after installation, everything else was intuitive
