### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by samnazarko** [djp952/pvr.hdhomerundvr#43]
Not an issue -- just a thanks on behalf of our OSMC users for producing binaries. 

We'd be happy to get this included in OSMC out of the box for Leia if you'd be interested.

Cheers

Sam

**Comment by djp952** [comment]
Hi! Sorry for the delay, I was on travel this past week.

First, you're welcome! I'm very glad that so many people have been able to use the code (generally) successfully, I'm a big fan of SiliconDust and the work they do out there.  I'm also a big fan of OSMC, you guys do a great job with your product, it's my go-to for the RPi without a doubt.

I'd be flattered if it could be included as part of OSMC, my main concerns are stability and release cadence, both on my side of things.  I always seem to have some bug lurking about that causes grief for some segment of the installed base.  I do my best to fix it for everyone, but often it takes longer than I'd like it to.  To date, I've also just 'released' whenever it seemed right to do so, either a significant change/fix or a Kodi milestone that would require rebuilding the Android/UWP baselines since they are repackaged to include the PVR binaries.

I also know that there are some folks out there trying feverishly to get an HDHomeRun DVR compatible PVR into the official Kodi code.  I think it's still generally based on my PVR (with my blessing, not that they needed it!), but that could be a factor for you as well, not sure you would want to get into any this-or-that type of thing where you may need to pull something from Kodi to include this instead.  Last I knew, theirs was also going to be called "pvr.hdhomerundvr", so high chance of name conflict there.

But hey - if you guys are cool with any inherent limitations I think it would be fantastic.  How would you want that to work, would you anticipate pulling the pre-compiled binaries into OSMC or would you anticipate source builds?

Also, it's worth noting that my Leia implementation isn't *quite* complete yet.  I have one outstanding todo in regard to stream times/timeshifting support.  What I have works, but it needs to be better.  Otherwise insofar as I am aware the Leia implementation should be ready to go.  I put in a couple Timer related PRs to Kodi that were accepted which got rid of my old todos, at least.

So yeah, sure, let's do it if you want to, let me know what steps/actions you would like me to take on this end and I'm very happy to do so!

**Comment by djp952** [comment]
Marking issue as closed for some housekeeping.  I still have no problem with this if you guys don't! Thanks!!
