### ISSUE TITLE
Leia PVR API 5.10.3

### ISSUE THREAD

**Issue by ssyspro** [djp952/pvr.hdhomerundvr#44]
Please update Leia to pvr API 5.10.3

**Comment by scottpinkston** [comment]
downloaded zuki.pvr.hdhomerundvr-linux-armhf-leia-1.3.5.6900.zip on coreelec 8.95.5 and getting this message: CAddonInstallJob[pvr.hdhomerundvr]: The dependency on kodi.binary.instance.pvr version 5.10.3 could not be satisfied.

**Comment by djp952** [comment]
There was a question here about the new build and coreelec? Anyway if you're watching for a reply the answer is that the Kodi version and PVR version have to match.  Such is the difficulty with trying to support beta/rc versions of Kodi.  The PVR API should be pretty much final at 5.10.3 now you can see if there is a newer build of coreelec (Leia Beta 5 or RC1) otherwise you can keep using the previous build of this PVR, there were no code changes (been crazy busy again sorry guys!). Let me know if you run into anything bad/weird I honestly just rebuilt and pushed out with almost zero testing this time :(

**Comment by scottpinkston** [comment]
It was coreelec based on beta 5.  Odd because the pvr in the version looks different than what is in rc1.
<?xml version="1.0" encoding="UTF-8"?>
<addon id="kodi.binary.instance.pvr" version="5.10.4" provider-name="Team Kodi">
  <backwards-compatibility abi="5.10.4"/>
  <requires>
    <import addon="xbmc.core" version="0.1.0"/>
  </requires>
</addon>

**Comment by djp952** [comment]
That is odd … the current maximum PVR version defined by Kodi is 5.10.3.

```
#define ADDON_INSTANCE_VERSION_PVR                    "5.10.3"
#define ADDON_INSTANCE_VERSION_PVR_MIN                "5.10.0"
```
Were you able to get things working?

**Comment by scottpinkston** [comment]
Yes, just reverted back a version of coreelec.


I think the 5.10.4 has to do with something they added for archives.   I'll
see what it looks like after they publish rc1.  I know what to look for
now.  Thanks!  Love what you have done for all of us.

**Comment by djp952** [comment]
No worries! Feel free to use these Issues for any questions/concerns in the future too!  I try to respond reasonably quickly :)

**Comment by edombroski** [comment]
I apologize in advance if this is not the the appropriate place for this question, but I'm not sure I wanted to create a new issue for it...I understand the CoreELEC folks bumped the PVR API version to 5.10.4 on their own accord, and as such this plugin can't be loaded.  Could you provide any guidance on hacking this to work on that platform? I'd be happy to get my hands dirty to try to hack this to work.  Any advice appreciated. Thanks.

**Comment by djp952** [comment]
No apologies necessary.  I went ahead and opened a new issue (more like a statement, I guess) about it here for everyone: https://github.com/djp952/pvr.hdhomerundvr/issues/52.

I'll copy/paste your question about hacking it over there and respond!
