### ISSUE TITLE
hdhomerundvr location as zipped?

### ISSUE THREAD

**Issue by MarkP2015** [djp952/pvr.hdhomerundvr#55]
I cannot understand where the zipped file is to be placed within the LibreELEC/Kodi folder or directory structure. I would assume it would not matter which Kodi release.

**Comment by djp952** [comment]
Hi!  Actually, you put the .zip file anywhere Kodi can find it.  You have to ask Kodi to install the addon from the .zip file.  Here are the steps for Leia, the other versions are as you assumed, every similar.  I do have pages out there specific for Jarvis and Krypton, though.

https://github.com/djp952/pvr.hdhomerundvr/wiki/Installation-on-Kodi-Leia

On Linux, I put the .zip file in my home directory, ~/ and that's usually where Kodi see "Home Directory" when you browse around to install the addon.  For libreELEC I use SCP (For a nice Windows-based GUI version try "WinSCP") to push the .zip to the machine, but you can also SSH into it and then use wget or curl to download the file directly.

But really, anywhere you can get at the .zip file from the Kodi Addon Browser's "Install from zip file" function is fine.

Let me know how you make out!

**Comment by gibxxi** [comment]
Hi Mike,

With relation to your built-in "Repo" for the HDHomeRunPVR DVR addon, I would suggest you give the repo itself a different name to that of the addon to avoid confusion as to which is which.

Regards,

Dan / Gib.

**Comment by djp952** [comment]
Hi Dan! 

The update repository information is built into the addon.xml of the addon package, so the name in Kodi matches the addon.  "repository.hdhomerundvr" isn't intended to be a public repo of stuff, it's only used for the private auto-updates of this addon.

I can see if I can change the repository name Kodi may show you or put in the addon database, but I'm pretty much locked into "repository.hdhomerundvr" at this point.  Changing it would break everyone that has already installed the addon.

Since I frequently misunderstand what you mean, please let me know if I missed the mark again.

**Comment by gibxxi** [comment]
Hi Mike,

If it's going to be a PITA to alter it, just leave it the way it is. Was just an observation, that's all.

:)

Dan / Gib.

**Comment by djp952** [comment]
Haven't heard back from @MarkP2015, I'm going to go ahead and mark this Issue as closed.

Dan, I am making a note to look into a PR or something along those lines for Kodi 19 "Matrix" to see if we can use a custom name to describe private Repositories in the addon.xml file :)  I think Team Kodi is a little tired of me.

I have intention, due to popular demand, to expand the repository out so that it can also auto-update Linux addons, perhaps something along the lines of what you are looking for will point itself out to me then as well.  Auto-updating binary addons on Linux isn't exactly "supported" right now, but with the right number of tweaks it can be made to work.

**Comment by gibxxi** [comment]
Hi Mike,

Rgr that. Will be monitoring the GitHub Repo (periodically) even if not actively posting issues / feedback. You know how to get in touch in any case.

Dan / Gib.
