### ISSUE TITLE
Can't view live video

### ISSUE THREAD

**Issue by gregwa1953** [djp952/pvr.hdhomerundvr#59]
I just installed pvr.hdhomerundvr on my kodi box running on a raspberry pi running latest version of OSMC.  I have a HDHomeRun Connect Quatro.

When I go to TV, I see that there is a recording being done (correct) and one set for later in the morning (correct).  The current recording was set on the "Official" app, and the later one was set via the pvr.hdhomerundvr app.

However, I can't watch any of the live stream from the pvr.hdhomerundvr app.  I get an error of "HDHomeRun DVR PVR Client: OpenLiveStream failed due to an exception: HTTP 404: Not Found"  

Is there something else that I need to install?  The Official app works fine, but I was interested in your app.

Thank you in advance,
Greg

**Comment by djp952** [comment]
Hi! There should be nothing else to install.  Sounds like the addon is having trouble talking to the HDHomeRun RECORD (DVR) engine.  The data about what may be recorded comes from the Internet, so that part sounds like it's working OK.

Is this just limited to Live TV -- can you play a Recorded TV file?

What I think we need is the Kodi log, it will have what URL(s) the addon is trying to get to for playback.  The file should be in ~/.kodi/temp and is called "kodi.log".  If you can try to open a live channel, let it fail, then wait a few minutes to make sure the log is written and grab that it should help a lot figuring out what the deal is.

In the meantime, there is an option that might let you watch Live TV.  If you go into the addon settings, under Advanced there is an option to stream Live TV directly from the tuner device(s).  You won't get timeshifting capabilities this way, but if it works then we know it's definitely something with not being able to talk to the DVR engine specifically.

Sorry for the difficulty!  There are lots and lots of OSMC users out there for the addon, it definitely works, we just need to figure out why it's not working for you!

**Comment by gregwa1953** [comment]
Thanks for the quick response.
Yes, it SEEMS to only be limited to viewing live tv.  The current recording is due to end in the next 25 minutes, so I can check that then (that one was done by the official app).  The one I set with your app (I like the interface so far) is scheduled to start just after the other one finishes.

I've attached the current log below.

[kodilog.zip](https://github.com/djp952/pvr.hdhomerundvr/files/3364713/kodilog.zip)

Digging a bit deeper, does TVHeadend need to be installed?  It might have taken over all of the tuners with the DVB Input system.  There is a thread here ... [](https://discourse.osmc.tv/t/osmc-and-hdhomerun-tuners/72872/3) that might be my problem.  I was just about to dig into that.

Thanks again for the quick response.

Greg

**Comment by gregwa1953** [comment]
The advanced setting to stream directly from the tuner DID work!  Thank you.  I'm not sure why I didn't see it earlier.  I guess I am having a case of OldTimers disease. 

Thanks again.  I'll leave this open for the time being just in case you come up with something else.

Greg

**Comment by djp952** [comment]
Thanks for the log! It looks like it's definitely having some problem finding the RECORD engine.  Streaming from tuner is OK, and that's what the HDHomeRun script plug-in appears to be doing as well.

The problem with going directly to the tuner is that you're missing out on timeshifting support (skip back and forward, etc), which is pretty much the coolest thing my addon can do that the other ones can't :)

As time allows, can you check something for me? In a web browser, navigate to http://ipv4-api.hdhomerun.com/discover.  You will get back a list of all your devices.  One of the devices in the list should have a "StorageID" value, this is the RECORD engine.  For example, here's what mine looks like:

```
 {
        "StorageID": "EF0291B8-9E70-40C8-BA4E-9AEE4BBE077C",
        "LocalIP": "192.168.0.220:60846",
        "BaseURL": "http://192.168.0.220:60846",
        "DiscoverURL": "http://192.168.0.220:60846/discover.json",
        "StorageURL": "http://192.168.0.220:60846/recorded_files.json"
    }
```

Is the "BaseURL" for yours coming back as "**http://192.168.1.207:65001**"?  This is the URL the addon is trying to use.

If that's correct, what do you see if you navigate to your BaseURL from the web browser?  You should get a page that says "HDHomeRun RECORD" at the top and has a System Status link.  If this comes up then the BaseURL is correct.

Let me know (again as time allows, no rush of course!).  This is kind of a weird problem, nobody that I am aware of has ever had this happen to them :)

It would probably also help if you can do both a Live TV session and a Recorded TV session for me in the log, the base URL should be the same for both, it's really odd that Recorded would work but Live wouldn't.  Worst case I can ask SiliconDust for some assistance as well, find out from them why it would return HTTP 404 on you.

**Comment by gregwa1953** [comment]
Thank you again for your responses.
First, and this might be the actual issue, I'm using Open Media Vault running on another Raspberry Pi.  I have followed the instructions at [](https://forum.silicondust.com/forum/viewtopic.php?f=126&t=65560) and am getting an error in the recording log from HDHR saying "RecordPath not specified".  I'm trying to fight that right now.  As to your above suggestions, doing the discover, I get:
`

  |  
-- | --
0 |  
DeviceID | "10773CED"
LocalIP | "192.168.1.132"
BaseURL | "http://192.168.1.132"
DiscoverURL | "http://192.168.1.132/discover.json"
LineupURL | "http://192.168.1.132/lineup.json"
1 |  
StorageID | "obscured"
LocalIP | "192.168.1.207:65001"
BaseURL | "http://192.168.1.207:65001"
DiscoverURL | "http://192.168.1.207:65001/discover.json"
StorageURL | "http://192.168.1.207:65001/recorded_files.json"

` 

By doing the jump to the recorded_files.json link I get an empty (well two byte file).

This is probably the problem.  I'll try to fight this forward through the OMV (OpenMediaVault) group.  (It's actually an unofficial product)

Thanks again,
Greg

**Comment by gregwa1953** [comment]
Yes.  It was the OMV setup.
I dug really deeply and found that the recorded_files path was wrong.  The share was under another folder in the "srv" folder of OMV.  After I fixed that, everything seems to work correctly.

As Gomer Pyle would say...
"Thank you Thank you Thank you!"

One other question.  TVheadend is NOT needed on my OSMC box, correct?

Greg

**Comment by djp952** [comment]
Awesome! Yeah, the RECORD engine uses the recorded_files path to buffer live TV too, so that makes perfect sense now :)

TVHeadend is NOT needed on the OSMC box.  Nothing external to the addon is required other than of course an HDHomeRun tuner and the RECORD engine running.  You don't need the SiliconDust app or any other software at all if you don't want it.  It's a one-stop shop.  Well, when it works - LOL.

I'll go ahead and leave this open for a bit in case you run into any other problems or have any questions.  Please feel free to open Issues any time, always glad to try and help!

**Comment by gregwa1953** [comment]
Thank you for the information on TVHeadend.  I will remove it.

Let me say that you guys have done a GREAT job with this app.  There are so many things that I like better here than in the "Official" plug in.

I'll be using it 100% of the time for my TV Viewing.  

I'll play with it for a bit more before I count on it and see if I can break it ;o)

Greg

**Comment by gregwa1953** [comment]
Ran your app all weekend and it works wonderfully.  PVR, DVR functions work great!  EPG is wonderful.
Please consider this issue closed with your wonderful help!
Thank you,
Greg
