### ISSUE TITLE
Installing DVR service on a Firestick

### ISSUE THREAD

**Issue by x60hz11** [djp952/pvr.hdhomerundvr#68]
Hey Michael, great addon but I was wondering if you could tell me what I'm doing wrong. I just installed the addon on my Firestick but I'm not able to rewind or ff live tv. It will pause and after a few seconds I get the Timeshift message but the rewind/ff buttons on the fs remote do nothing. Also I do not see any rewind/ff icons on the osd. I do have a DVR subscription activated HDHOMERUN tuner.  I installed this a few months ago on a Windows machine and it worked well. But with this firestick I can't figure it out. Thanks!!

**Comment by djp952** [comment]
Hello! There are two reasons the addon would do this, it either wasn't able to find the HDHomeRun RECORD instance on your network, or it found it but is getting an error trying to communicate with it.

We can check the former via Kodi ... if you go into Settings / PVR & Live TV, make sure the level at the bottom is set to "Advanced".  You should see a "Client Specific" category to choose.  From there,  pick "Client specific settings".  This brings up a small menu, the first item is "List discovered devices" -- pick that one.  Do you see an entry for an "HDHomeRun RECORD" device?

If you **do not** see the device listed, the addon couldn't find it.  This could be due to a network configuration, perhaps a firewall setting on the wifi router, a subnet configuration, or it's just not turned on right now.  Let's assume it's turned on :)  There is an addon option to use the HDHomeRun cloud services to find your devices instead of trying to find them on it's own.  We can try turning that on via:

Addons / Addon browser / My addons / PVR Clients / HDHomeRun DVR PVR Client / Configure / Advanced / **Use HTTP cloud-based discovery**

When you turn this on and save it, it will go out and check immediately.  So ... as tedious as it is, head back to the PVR & Live TV "Client specific settings" and see if it shows up now.

If the HDHomeRun RECORD did show up and you can't FF/RW or see your record, we'd have to have a look in the Kodi log file to find out what error occurred trying to open the stream.  Unfortunately I don't have a UI-based way to find that out (but seems like a nice thing to add).  You will need to grab the kodi.log from the device, probably over ADB, but there may be other ways depending on what you are comfortable with.

If you pushed the addon to the device using ADB, you can also grab the log that way.  What you'll want to do is restart Kodi, try to play a channel or two, and then wait a tick for the log to be written.  The file you'll want to grab is:

/sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

Let me know if you want any assistance with getting the log file.  If you get it, you can hit me up with a copy of the log file at djp952 AT gmail DOT com, very happy to look it over.

Long-winded response, but hopefully will get you rolling!

**Comment by djp952** [comment]
Problem was determined to be the HDHomeRun RECORD instance not present on the network due to the switch from Windows where it was more obvious how to install it than it is on Android.  Marking issue as closed.

Please don't hesitate to open any new issues or contact me for, well, pretty much anything!  Thank you for using the addon and I hope that it performs well for you moving forward sir!
